services:
  - type: web
    name: bragging-rights-stats
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn serve:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
